# Generated by Django 5.2.7 on 2025-10-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
    ]
