# Generated by Django 5.2.7 on 2025-11-03 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0002_initial_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_lecionadas', to='professores.professor'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
